### ISSUE TITLE
Unhandled 'error' event  Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by oussaka** [ethancfchen/generator-bombyx-api-php#1]
Yo,
I have this error when i run yo bombyx-api-php

My config is : node v6.10.0 npm v 3.10.10

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/home/vagrant/.config/yarn/global/node_modules/generator-bombyx/generators/app/index.js:73:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as bombyx:app] (/home/vagrant/.config/yarn/global/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/home/vagrant/.config/yarn/global/node_modules/yeoman-environment/lib/store.js:64:35)
```

**Comment by ethancfchen** [comment]
I'll check tomorrow, maybe I'll change the ES6 syntax back to ES5.
Thanks.

**Comment by ethancfchen** [comment]
@oussaka Please upgrade to v0.7.0 and give it a try, thanks.

**Comment by oussaka** [comment]
I confirm, it works with ^0.7.0 version
👍

**Comment by ethancfchen** [comment]
@oussaka Thanks for confirmation.
